FROM python:3.12-slim

WORKDIR /app

COPY requirements-dev.txt .

RUN pip install --no-cache-dir -r requirements-dev.txt

COPY src ./src
COPY scripts ./scripts
COPY migrations ./migrations
COPY alembic.ini .
COPY streamlit_app.py .
COPY docker/entrypoint.sh ./docker/entrypoint.sh

RUN mkdir -p \
    data/raw/sap \
    data/raw/uploads \
    data/processed

RUN chmod +x ./docker/entrypoint.sh

EXPOSE 8501

ENTRYPOINT ["./docker/entrypoint.sh"]