"""add chunks and document hash

Revision ID: 4e358f02f174
Revises: f1f5d6cf5b70
Create Date: 2026-09-06 15:35:27.265883

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '4e358f02f174'
down_revision: str | Sequence[str] | None = 'f1f5d6cf5b70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
