"""add language to documents

Revision ID: 54cbc1971724
Revises: 80091cdc0b8c
Create Date: 2026-09-06 15:13:21.931834

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '54cbc1971724'
down_revision: str | Sequence[str] | None = '80091cdc0b8c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('language', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'language')
    # ### end Alembic commands ###
