"""add chunks and document hash

Revision ID: f1f5d6cf5b70
Revises: 54cbc1971724
Create Date: 2026-09-06 15:32:16.196089

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1f5d6cf5b70'
down_revision: str | Sequence[str] | None = '54cbc1971724'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.alter_column('documents', 'source',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('documents', 'source',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###
